- name: Intall PyCurl
  apt: pkg="python-pycurl" state=present

- name: Add apt-key
  apt_key: keyserver="hkp://keyserver.ubuntu.com:80" id="7F0CEB10" state=present

- name: Add mongodb repo
  apt_repository: repo="deb http://downloads-distro.mongodb.org/repo/ubuntu-upstart dist 10gen" state=present

- name: Install MongoDB
  apt: pkg="mongodb-org" state=present force=yes

- name: Ensure MongoDB is running
  service: name=mongod state=started

- name: Install pymongo if users are to be added.
  apt: pkg={{ item }}
  with_items: python-pymongo
  when: mongodb_users|length > 0

- name: Add MongoDB users
  mongodb_user: >
    database="foo"
    name="{{ item.username }}"
    password="{{ item.password }}"
    roles="{{ item.roles | default('readWrite,dbAdmin,userAdmin') }}"
    state="present"
  with_items: mongodb_users
  notify: restart mongodb
  when: mongodb_users|length > 0